apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-webapp-nodejs
  name: simple-webapp-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webapp-nodejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-webapp-nodejs
    spec:
      containers:
      - image: gehadgkamel/simple-webapp-nodejs:latest
        name: simple-webapp-nodejs
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-connection
                key: POSTGRES_HOST
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: postgres-connection
                key: POSTGRES_PORT
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-connection
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-connection
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-connection
                key: POSTGRES_PASSWORD
status: {}
